### PR TITLE
I am not coming tomorrow. Please send notes.

### PR DESCRIPTION
**Pull request by shanks28**
just think hard on what the code does and merge this ...also dont use jupiter notebook because i need professional subscription to 
edit.

### CODE REVIEW

**Comment by AashishNandakumar** [comment]
Give me some time

**Comment by shanks28** [comment]
Ok sure.

**Comment by AashishNandakumar** [comment]
> Ok sure.

Request you to change the file name to "Day_2_palindrome_updated"

**Comment by AashishNandakumar** [comment]
> Ok sure.

Request you to change the file name to "Day2_1b_palindrome_updated"

**Comment by shanks28** [comment]
nin ajji do it yourself man

**Comment by shanks28** [comment]
i mean just delete the file after you update your notebook file.

**Comment by AashishNandakumar** [comment]
> 

Just do it man lazy fellow

**Comment by ad4r5hgs** [comment]
How to make a pudina milkshake ?

**Comment by AashishNandakumar** [comment]
> How to make a pudina milkshake ?

This has become the new whatsApp

**Comment by shanks28** [comment]
what does this mean?

**Comment by AashishNandakumar** [comment]
> what does this mean?

"nin ajji"

**Comment by shanks28** [comment]
why in quotes ?

**Comment by AashishNandakumar** [comment]
> why in quotes ?



> what does this mean?

...

**Comment by shanks28** [comment]
lol

**Pull request merged**
